name: Trigger-Build-Deploy
on:
    push:
        branches:
            - devdeploy
            - master
    workflow_dispatch:

jobs:
    call-build:
        uses: hiddenderek/wkfl-microservice-build/.github/workflows/build.yml@v1.6.2
        with:
            region: us-west-2
        secrets:
            AWS_CREDS: ${{ toJSON(github.event.deployment.payload.aws) }}
