name: Deploy Service
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    uses: hiddenderek/wkfl-microservice-build/.github/workflows/build.yml@main
    with:
      environment: dev
      region: us-east-1
      build-branch: develop
    secrets:
      # GitHub token for accessing private repo
      github-token: ${{ secrets.REPO_TOKEN }}
      # AWS secrets
      aws-key: ${{ secrets.AWSKEY }}
      aws-secret: ${{ secrets.AWSSECRET }}
      aws-dev-account: ${{ secrets.AWS_DEV_ACCOUNT }}
      aws-qa-account: ${{ secrets.AWS_QA_ACCOUNT }}
      aws-prod-account: ${{ secrets.AWS_PROD_ACCOUNT }}
      stop-bastion-after-deploy: ${{ secrets.STOP_BASTION_AFTER_DEPLOY }}

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    uses: hiddenderek/wkfl-microservice-build/.github/workflows/build.yml@main
    with:
      environment: dev
      region: us-east-1
      build-branch: main
    secrets:
      # GitHub token for accessing private repo
      github-token: ${{ secrets.REPO_TOKEN }}
      # AWS secrets
      aws-key: ${{ secrets.AWSKEY }}
      aws-secret: ${{ secrets.AWSSECRET }}
      aws-dev-account: ${{ secrets.AWS_DEV_ACCOUNT }}
      aws-qa-account: ${{ secrets.AWS_QA_ACCOUNT }}
      aws-prod-account: ${{ secrets.AWS_PROD_ACCOUNT }}
      stop-bastion-after-deploy: ${{ secrets.STOP_BASTION_AFTER_DEPLOY }}
